# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/josephburnett/jd
%global goipath         github.com/josephburnett/jd
Version:                1.7.1

%gometa -f

%global common_description %{expand:
JSON diff and patch.}

%global golicenses      LICENSE
%global godocs          README.md RELEASE_NOTES.md

Name:           %{goname}
Release:        %autorelease
Summary:        JSON diff and patch

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: golang(github.com/go-openapi/jsonpointer)
BuildRequires: golang(gopkg.in/yaml.v2)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%build
%gobuild -o %{gobuilddir}/bin/jd %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md RELEASE_NOTES.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
